services:
        app:
                image: bitnami/laravel:10.3.3-debian-12-r13
                restart: unless-stopped
                container_name: third_party_integration
                tty: true
                ports: 
                        - 8000:8000
                volumes:
                        - ./:/app
                        - ./php.ini:/opt/bitnami/php/etc/php.ini
